refactored getFeatureInfo
citysciencelab/open-city-toolkit pull request #164
Opened 2021-02-16 09:07 UTC by JowieXiang

sorted out *getFeatureInfo* feature from *Transerve's* PR #159

2021-02-21 11:48 UTC, janbehrens requested changes
Suggestions:
- open popup on click instead of doubleclick
- make the popup larger and improve its style
- don't show "cat" and tags with no value

2021-02-21 11:48 UTC, janbehrens commented on webapp/views/map/betterWMS/L.TileLayer.BetterWMS.js
> +};
There are 38 eslint problems in this file.

2021-02-26 17:17 UTC, JowieXiang commented
> Suggestions:
> 
> * open popup on click instead of doubleclick
> * make the popup larger and improve its style
> * don't show "cat" and attributes with no value

Added corresponding changes in the new commits.

2021-02-28 17:17 UTC, janbehrens commented on webapp/views/map/script.js
> +  return service.type === 'vector' ? L.tileLayer.betterWms(vectorWMS, service) : L.tileLayer.betterWms(rasterWMS, service)
Isn't it quite useless for raster layers?

2021-02-28 18:16 UTC, janbehrens approved these changes

2021-02-28 18:16 UTC, merged